container:
  image: gradle:jdk8

check_task:
  gradle_cache:
    folder: ~/.gradle/caches
  check_script: gradle check
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - rm -f ~/.gradle/caches/user-id.txt
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete

deploy_task:
  only_if: $CIRRUS_TAG != ''
  env:
    GRADLE_PUBLISH_KEY: ENCRYPTED[7db1342c0b7bc4070cf530514dbc09f13f074e6562ccee03d2bd4edd515d145e99ccc7ea9ec36e813f86f28b0188a768]
    gradlePublishSecret: ENCRYPTED[619779efa1d37ba15eb736ffbb3432fddf6c0f9fd2174a08801e9a076ef4a2ede4e8c58b0f8e3185e454b1990966d349]
  upload_script: gradle publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=<secret>